"""Tests for the argv/env equivalence harness. #235, #264, #149

The port is not equivalent to the shell by blank equality; it is equivalent
except where a bug is being fixed, and each fix is a deliberate difference. So
assertion 3 does not say "the argv are the same"; it pins the *sanctioned*
difference -- the shell's `--skip-tensor-gate` (which #264 removed from run.py)
against the port's `--allow-unverified-route`, plus the `--server-log` the port
carries because the shell redirected stdout instead.

The fixtures under `tests/fixtures/equiv/` are the recorded emissions of both
drivers; they were generated by `scripts/gen_equiv_fixtures.py` and committed,
so these tests run offline with no driver loop, server, or GPU.
"""

from __future__ import annotations

import datetime as dt
import os
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
for sub in ("scripts", "scripts/lib", "benchmarks/agent"):
    sys.path.insert(0, str(ROOT / sub))

import equiv
import pytest
import route_ab_report

FIXTURES = ROOT / "tests" / "fixtures" / "equiv"
PORT = FIXTURES / "route_agent_ab-port.jsonl"
SHELL = FIXTURES / "route_agent_ab-shell.jsonl"

TAG = "t-sweep1"


# ------------------------------------------------------------------ the model


def test_invocation_roundtrips_through_jsonl(tmp_path) -> None:
    inv = equiv.Invocation("ds4-server", "t", ["--metal", "-m", "m"], {"A": "1"})
    path = tmp_path / "rec.jsonl"
    equiv.record(path, inv)
    got = equiv.load(path)
    assert got == [inv]
    assert got[0].program == "ds4-server"
    assert got[0].argv == ("--metal", "-m", "m")
    assert got[0].env == {"A": "1"}


def test_load_skips_blank_and_comment_lines(tmp_path) -> None:
    path = tmp_path / "rec.jsonl"
    path.write_text(
        "# source: route_agent_ab.sh\n"
        '{"program": "run.py", "arm": "t", "argv": ["--backend"], "env": {}}\n'
        "\n"
    )
    got = equiv.load(path)
    assert len(got) == 1 and got[0].program == "run.py"


def test_by_program_filters(tmp_path) -> None:
    p = tmp_path / "r.jsonl"
    equiv.record(p, equiv.Invocation("ds4-server", "t", [], {}))
    equiv.record(p, equiv.Invocation("run.py", "t", [], {}))
    assert [i.program for i in equiv.by_program(equiv.load(p), "run.py")] == ["run.py"]


def test_env_key_state_distinguishes_every_meaning() -> None:
    assert equiv.env_key_state({}, "K") == "absent"
    assert equiv.env_key_state({"K": ""}, "K") == "empty"
    assert equiv.env_key_state({"K": "1"}, "K") == "set:1"


# ---------------------------------------------------------- the shim itself


def test_write_shim_records_argv_and_env_through_child_run(tmp_path) -> None:
    """The shim works, and `child.run`'s unset reaches the recorded child.

    The host exports an operator's leftover of the #149 variable; the reference
    arm must strip it anyway, and the fake proves it by recording the child's
    env without the key. This is the mechanism assertion 2 rests on.
    """
    out = tmp_path / "rec.jsonl"
    shim = equiv.write_shim(tmp_path / "shim", out)
    for arm in ("t", "r"):
        if arm == "t":
            equiv.run_fake(
                shim,
                "ds4-server",
                arm,
                ["--port", "8000"],
                {equiv.TENSOR_ENV: "1"},
                (),
                out,
                tmp_path / "spawn.log",
                via="ds4-server",
            )
        else:
            equiv.run_fake(
                shim,
                "ds4-server",
                arm,
                ["--port", "8000"],
                {},
                (equiv.TENSOR_ENV,),
                out,
                tmp_path / "spawn.log",
                via="ds4-server",
            )
    recs = equiv.by_program(equiv.load(out), "ds4-server")
    assert len(recs) == 2
    assert equiv.env_key_state(recs[0].env, equiv.TENSOR_ENV) == "set:1"
    assert equiv.env_key_state(recs[1].env, equiv.TENSOR_ENV) == "absent"


def test_uv_fake_default_executes_nothing(tmp_path) -> None:
    """Fail-closed: with no run_real, an unlisted script is recorded, not run.

    The default `run_real=()` is the safe state. A script that would be loud if
    it ran -- one that writes a marker file -- must be recorded and exited 0,
    with the marker never appearing. This is the guard that a differential
    which forgets to name its helpers gets a recorded no-op, not a real server.
    """
    import os
    import subprocess

    out = tmp_path / "rec.jsonl"
    uv = equiv.write_uv_fake_running_real(tmp_path / "uv", out, ROOT)
    marker = tmp_path / "loud-ran"
    loud = tmp_path / "loud.py"
    loud.write_text(
        f"#!/usr/bin/env python3\nopen({str(marker)!r}, 'w').write('ran')\n"
    )
    env = {
        "EQUIV_OUT": str(out),
        "EQUIV_ARM": "shell",
        "PATH": os.environ.get("PATH", ""),
    }
    got = subprocess.run(
        [sys.executable, str(uv), "run", "python", str(loud)],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert got.returncode == 0, got.stderr
    assert not marker.exists(), "the unlisted script ran for real"
    recs = equiv.load(out)
    assert len(recs) == 1
    assert recs[0].program == "loud.py"


def test_inline_c_executes_for_real_not_recorded(tmp_path) -> None:
    """`uv run python -c '<code>'` runs the code, because it is the shell's own
    source text inlined, not an external program.

    `ds4_record_route` and `worktree_code_dirty` invoke it. A fake that records
    `-c` and exits 0 would give the shell nothing while the port runs the same
    logic in-process -- an asymmetry that manufactures differences. The code
    must run for real, and the invocation must still be recorded.
    """
    import os
    import subprocess

    out = tmp_path / "rec.jsonl"
    uv = equiv.write_uv_fake_running_real(tmp_path / "uv", out, ROOT)
    marker = tmp_path / "c-ran"
    code = f"open({str(marker)!r}, 'w').write('ran')"
    env = {
        "EQUIV_OUT": str(out),
        "EQUIV_ARM": "shell",
        "PATH": os.environ.get("PATH", ""),
    }
    got = subprocess.run(
        [sys.executable, str(uv), "run", "python", "-c", code],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert got.returncode == 0, got.stderr
    assert marker.exists(), "the inline code did not run for real"
    recs = equiv.load(out)
    assert len(recs) == 1
    assert recs[0].program == "-c"


def test_fake_shim_emits_the_real_on_line_and_the_off_assumption(tmp_path) -> None:
    """The shim's ON line is the engine's; the OFF line is a stated assumption.

    The ON arm's startup line is read from the real-run excerpt
    `shim-strip-on.log`, so the fake prints exactly what the shim printed. The
    OFF line has no real example in the repo, so the fake emits the driver's
    own grep target and the README records the assumption. Both arms must reach
    the driver's `grep -q "$want"` check.
    """
    import os
    import subprocess

    out = tmp_path / "rec.jsonl"
    uv = equiv.write_uv_fake_running_real(tmp_path / "uv", out, ROOT, shim=True)
    base = {
        "EQUIV_OUT": str(out),
        "EQUIV_ARM": "shell",
        "PATH": os.environ.get("PATH", ""),
    }
    on = subprocess.run(
        [sys.executable, str(uv), "run", "python", "ds4_qwen_tool_shim.py"],
        env=base,
        capture_output=True,
        text=True,
        check=False,
    )
    assert on.returncode == 0, on.stderr
    # Read from the fixture, not retyped. A constant typed here would agree
    # with a fake that was typed from the same memory, which is exactly how
    # the OFF line stayed wrong for months.
    assert mode_line("shim-strip-on.log") in on.stdout
    off_env = dict(base, SHIM_NO_STRIP="1")
    off = subprocess.run(
        [sys.executable, str(uv), "run", "python", "ds4_qwen_tool_shim.py"],
        env=off_env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert off.returncode == 0, off.stderr
    # The WHOLE line, not the prefix. Until 2026-09-09 the fake printed a bare
    # `scaffolding strip: OFF` -- a line the shim has never produced -- and
    # this assertion passed on it, because `scaffolding strip: OFF` is a
    # substring of the real `scaffolding strip: OFF (experiment arm)
    # (#112 remedy 2)`. So did `strip_toggle_ab.sh:156`, which greps with
    # `grep -q "$want"`. Two substring matchers agreeing with each other is
    # not evidence about the shim.
    want = mode_line("shim-strip-off.log")
    assert "(experiment arm)" in want, "the OFF fixture lost its real text"
    assert want in off.stdout, f"want {want!r}, got {off.stdout!r}"


def mode_line(fixture: str) -> str:
    """The shim's `scaffolding strip: ...` line, out of a real-run excerpt.

    One owner for the text. The fake reads these same two files, so a fixture
    that loses its real wording fails here rather than quietly making the
    differential agree with itself.
    """
    path = ROOT / "tests" / "fixtures" / "logs" / fixture
    for raw in path.read_text().splitlines():
        if "scaffolding strip:" in raw:
            return raw.split("INFO ", 1)[-1].strip()
    raise AssertionError(f"{fixture} carries no strip line")


def test_fake_ds4_server_emits_the_real_graph_excerpt(tmp_path) -> None:
    """The fake's graph line is the engine's, not a hand-typed string.

    The heavy drivers grep the server log for `Qwen graph allocated` and
    `MTP=off` / `MTP=Q4_K/Q8_0/BF16` before they will run a measurement. The
    fake must emit those markers so the real `.sh` reaches the argv-construction
    point offline -- but the line must come from the real-run excerpt under
    `tests/fixtures/logs/`, never be composed here. This runs the fake both
    ways and asserts its stdout carries the markers the drivers grep for.
    """
    import os
    import subprocess

    out = tmp_path / "rec.jsonl"
    tree = tmp_path / "tree"
    fake = equiv.write_fake_ds4_server(tree, out, ROOT)
    env = {
        "EQUIV_OUT": str(out),
        "EQUIV_ARM": "shell",
        "PATH": os.environ.get("PATH", ""),
    }
    mtp = subprocess.run(
        [sys.executable, str(fake), "--mtp-model", "m.gguf"],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert mtp.returncode == 0, mtp.stderr
    assert "Qwen graph allocated" in mtp.stdout
    assert "MTP=Q4_K/Q8_0/BF16" in mtp.stdout
    assert "MTP sidecar loaded" in mtp.stdout
    plain = subprocess.run(
        [sys.executable, str(fake)],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    assert plain.returncode == 0, plain.stderr
    assert "Qwen graph allocated" in plain.stdout
    assert "MTP=off" in plain.stdout
    assert "MTP sidecar loaded" not in plain.stdout
    # both arms recorded their argv+env
    recs = equiv.by_program(equiv.load(out), "ds4-server")
    assert len(recs) == 2
    assert recs[0].argv == ("--mtp-model", "m.gguf")


def test_no_fixture_carries_env_outside_the_controlled_base() -> None:
    """A committed fixture must not record the operator's whole environment.

    The recording fakes capture `os.environ` wholesale. That is fine for a
    tmp-scoped capture, but a committed fixture that carried `LC_CTYPE` or a
    token would be a secret in the repo -- and gitleaks only catches keys that
    look like tokens. This asserts every env key in every fixture is one the
    driver set or the harness controls.
    """
    leaks = []
    for path in sorted(FIXTURES.glob("*.jsonl")):
        for inv in equiv.load(path):
            for key in inv.env:
                if key not in equiv.CONTROLLED_ENV_KEYS:
                    leaks.append(f"{path.name}:{inv.program}:{key}")
    assert not leaks, f"fixtures carry env outside the controlled base: {leaks}"


# ---------------------------------------------------------- run.py's flags


def test_declared_run_flags_reads_live_source(tmp_path) -> None:
    fake = tmp_path / "run.py"
    fake.write_text(
        "import argparse\n"
        "p = argparse.ArgumentParser()\n"
        "p.add_argument('--trials', type=int, default=1)\n"
        "p.add_argument('-v', '--verbose', action='store_true')\n"
    )
    flags = equiv.declared_run_flags(fake)
    for want in ("--trials", "-v", "--verbose", "-h", "--help"):
        assert want in flags


def test_run_py_declares_the_ports_flag_not_the_shells():
    flags = equiv.declared_run_flags()
    assert "--allow-unverified-route" in flags
    assert "--server-log" in flags
    assert "--skip-tensor-gate" not in flags  # #264 removed it


def test_no_run_py_flag_is_declared_non_literally():
    """A non-literal add_argument would leave the declared set silently.

    `declared_run_flags` sees only ast.Constant string flags. The day run.py
    writes `parser.add_argument(*SPEC)` or `add_argument(f"--{name}")`, that
    flag disappears from the set and the #264 gate starts rejecting a driver
    that is correct -- a loud refusal that blames the wrong file. This asserts
    the real run.py declares every flag literally, so the gate's claim of
    reading the live source stays honest.
    """
    assert equiv.non_literal_flag_tests() == []


def test_non_literal_flag_tests_fires_on_a_splat(tmp_path) -> None:
    fake = tmp_path / "run.py"
    fake.write_text(
        "import argparse\n"
        "p = argparse.ArgumentParser()\n"
        "SPEC = ('--trials', '--verbose')\n"
        "p.add_argument(*SPEC)\n"
        "p.add_argument(f'--{name}')\n"
    )
    got = equiv.non_literal_flag_tests(fake)
    assert len(got) == 2, got
    assert "add_argument(*SPEC)" in " ".join(got)
    assert "add_argument" in got[1]


def test_non_literal_flag_tests_silent_on_literals(tmp_path) -> None:
    fake = tmp_path / "run.py"
    fake.write_text(
        "import argparse\n"
        "p = argparse.ArgumentParser()\n"
        "p.add_argument('--trials', '--verbose')\n"
        "p.add_argument('-v')\n"
    )
    assert equiv.non_literal_flag_tests(fake) == []


def test_assert_flags_declared_ignores_values_and_names_unknown():
    flags = frozenset({"--trials", "--no-lock"})
    equiv.assert_flags_declared(["--trials", "3", "--no-lock"], flags)  # no raise
    with pytest.raises(AssertionError):
        equiv.assert_flags_declared(["--trials", "3", "--skip-tensor-gate"], flags)
    # a value is not a flag
    equiv.assert_flags_declared(["--trials", "3", "path/to/model"], flags)


# ---------------------------------------------------- canonical / argv diff


def test_canonical_drops_flag_order_keeps_flag_value():
    flags = frozenset({"--a", "--b", "--v"})
    c1 = equiv.canonical(["--a", "1", "--b", "2"], flags)
    c2 = equiv.canonical(["--b", "2", "--a", "1"], flags)
    assert c1 == c2
    # flipping a flag's value is a change
    assert equiv.canonical(["--a", "1"], flags) != equiv.canonical(["--a", "2"], flags)


def test_canonical_does_not_glue_an_unknown_flag_onto_the_previous():
    flags = frozenset({"--no-lock"})
    got = equiv.canonical(["--no-lock", "--skip-tensor-gate"], flags)
    assert ("--skip-tensor-gate",) in got  # it opens its own pair, not a value
    assert ("--no-lock",) in got


def test_argv_difference_only_reports_the_two_sides_true_diff():
    declared = frozenset({"--no-lock", "--a"})
    shell_only, port_only = equiv.argv_difference(
        ["--no-lock", "--skip-tensor-gate"], ["--no-lock", "--a"], declared
    )
    assert shell_only == {("--skip-tensor-gate",)}
    assert port_only == {("--a",)}
    # --no-lock appears on both, so it is not in the diff


# ---------------------------------------------- assertion 4: the tag consumer


def route_consumer(tag: str, tmp_path: pathlib.Path) -> str | None:
    """route_ab_report's own window parser, fed one sweep line."""
    run_dir = tmp_path / "run"
    run_dir.mkdir(exist_ok=True)
    (run_dir / "sweep-order.txt").write_text(f"{tag} 08:00:00 08:10:00\n")
    # tz-aware is only to satisfy ruff: read_windows reads the anchor's .date()
    # and then builds naive windows, so awareness is irrelevant to the result.
    anchor = dt.datetime(2026, 9, 9, 8, tzinfo=dt.UTC)
    wins = route_ab_report.read_windows(run_dir, "t-sweep", "r-sweep", anchor)
    return wins[0][1] if wins else None


def test_the_driver_tag_roundtrips_through_its_report(tmp_path):
    equiv.assert_tag_roundtrips(TAG, "t", lambda t: route_consumer(t, tmp_path))


def test_the_bare_default_tag_is_unparseable(tmp_path):
    """Without tag_for the ab_driver default ships a tag nobody can read."""
    for bad in equiv.default_tags():
        assert route_consumer(bad, tmp_path) is None, bad


# ---------------------------------------------- the committed fixtures (1-3)


def test_assertion1_the_ports_flags_are_all_declared():
    flags = equiv.declared_run_flags()
    for run in equiv.by_program(equiv.load(PORT), "run.py"):
        equiv.assert_flags_declared(run.argv, flags)


def test_assertion1_the_shells_skip_tensor_gate_is_gone():
    """The shell still passes --skip-tensor-gate (#264); run.py dropped it.

    This is why the harness records the shell as the *expected-broken* side,
    not as a target the port must match: had the port reproduced the shell's
    flag, assertion 1 would fail on the port too.
    """
    flags = equiv.declared_run_flags()
    shell_run = equiv.by_program(equiv.load(SHELL), "run.py")[0]
    with pytest.raises(AssertionError):
        equiv.assert_flags_declared(shell_run.argv, flags)


def test_assertion2_env_difference_matches_between_the_drivers():
    for fixture in (SHELL, PORT):
        equiv.assert_arm_env_delta(equiv.load(fixture), key=equiv.TENSOR_ENV)


def test_assertion2_ds4_server_only_not_run_py(tmp_path) -> None:
    """The run.py client is not asserted; a leftover on it fails nothing.

    The experiment's variable is the route the *server* takes, so the env delta
    is asserted on the server's child only. To prove the scope, give the run.py
    client a state that would fail assertion 2 if it were checked (a leftover
    "7" that is neither set:1 nor absent) and assert `assert_arm_env_delta`
    still passes -- the client is simply not the subject of #149, and the port
    must not be forced to strip the operator's export from its client env.
    """
    out = tmp_path / "rec.jsonl"
    shim = equiv.write_shim(tmp_path / "shim", out)
    equiv.run_fake(
        shim,
        "ds4-server",
        "r",
        [],
        {},
        (equiv.TENSOR_ENV,),
        out,
        tmp_path / "s.log",
        via="ds4-server",
    )
    equiv.run_fake(
        shim,
        "run.py",
        "r",
        [],
        {equiv.TENSOR_ENV: "7"},
        (),
        out,
        tmp_path / "s.log",
        via="run.py",
    )
    recs = equiv.load(out)
    equiv.assert_arm_env_delta(recs, key=equiv.TENSOR_ENV)  # only checks server
    run_env = equiv.by_program(recs, "run.py")[0].env
    assert equiv.env_key_state(run_env, equiv.TENSOR_ENV) == "set:7"


def test_assertion3_server_argv_is_identical_between_the_drivers():
    flags = equiv.declared_run_flags()
    for arm in ("t", "r"):
        shell_srv = equiv.by_program(equiv.load(SHELL), "ds4-server")
        port_srv = equiv.by_program(equiv.load(PORT), "ds4-server")
        s = next(x for x in shell_srv if x.arm == arm)
        p = next(x for x in port_srv if x.arm == arm)
        assert equiv.canonical(s.argv, flags) == equiv.canonical(p.argv, flags)


def test_assertion3_run_py_diff_is_exactly_the_sanctioned_fixes():
    flags = equiv.declared_run_flags()
    shell_run = equiv.by_program(equiv.load(SHELL), "run.py")[0].argv
    port_run = equiv.by_program(equiv.load(PORT), "run.py")[0].argv
    shell_only, port_only = equiv.argv_difference(shell_run, port_run, flags)
    assert shell_only == {("--skip-tensor-gate",)}  # #264, and only that
    # the port adds exactly the #264 fix and the --server-log (the shell
    # redirected stdout to a log instead of telling run.py where to write).
    assert port_only == {
        ("--allow-unverified-route",),
        ("--server-log", "out/server-t-sweep1.log"),
    }
    # both sides name the same backend, trials, client -- the measurement inputs
    for side in (shell_run, port_run):
        assert "--backend" in side and "--client" in side and "--trials" in side


# --------------------------------------------------------- uv's own flags


@pytest.mark.parametrize("write", ["write_uv_fake", "write_uv_fake_running_real"])
@pytest.mark.parametrize(
    "extra",
    [[], ["--frozen"], ["--frozen", "--no-sync"]],
    ids=["bare", "frozen", "two"],
)
def test_a_uv_flag_does_not_change_what_the_fake_records(
    tmp_path, write, extra
) -> None:
    """`uv run --frozen python X` records as X, not as uv.

    Both fakes used to test `args[1] == "python"`, which is false the moment a
    uv flag appears -- and the else branch calls the program "uv" and hands it
    the WHOLE command line as argv. That is not a crash: the invocation still
    records, still compares, and compares equal to every other mis-parsed call,
    because they all become the same program with different argv. A pair whose
    two sides spell the flag differently would then differ in argv[0..n] rather
    than in the thing under test, and a pair that spells it the same way agrees
    for a reason that has nothing to do with the port.

    `stack_agent_ab.sh:339` is the live `--frozen` call site, so this is one
    edit away from mattering rather than hypothetical.
    """
    out = tmp_path / f"{write}-{len(extra)}.jsonl"
    # write_uv_fake takes no repo: it never execs anything, so it has no need
    # of one. The pair is called through getattr precisely so the two parsers
    # are asserted by the same test rather than by two that can drift.
    make = getattr(equiv, write)
    target = tmp_path / f"uv-{write}-{len(extra)}"
    uv = (
        make(target, out, ROOT) if write.endswith("running_real") else make(target, out)
    )
    subprocess.run(
        [sys.executable, str(uv), "run", *extra, "python", "preflight.py", "--x"],
        env={**os.environ, "EQUIV_OUT": str(out), "EQUIV_ARM": "a"},
        capture_output=True,
        text=True,
        check=True,
    )
    recs = equiv.load(out)
    assert [r.program for r in recs] == ["preflight.py"]
    assert recs[0].argv == ("--x",)


@pytest.mark.parametrize("write", ["write_uv_fake", "write_uv_fake_running_real"])
def test_a_bare_uv_run_python_does_not_crash_the_fake(tmp_path, write) -> None:
    """`uv run python` with no script names no program. It must not raise.

    Reading past the end is an IndexError, which the running-real fake's
    `except ValueError` did not cover -- a fake that dies here reports as the
    DRIVER failing, which is a long way from the truth.
    """
    out = tmp_path / f"{write}-bare.jsonl"
    make = getattr(equiv, write)
    target = tmp_path / f"uv-bare-{write}"
    uv = (
        make(target, out, ROOT) if write.endswith("running_real") else make(target, out)
    )
    got = subprocess.run(
        [sys.executable, str(uv), "run", "python"],
        env={**os.environ, "EQUIV_OUT": str(out), "EQUIV_ARM": "a"},
        capture_output=True,
        text=True,
        # check=False deliberately: the assertion below reports the fake's own
        # traceback, which is the whole point. CalledProcessError would hide it.
        check=False,
    )
    assert got.returncode == 0, got.stderr
    assert [r.program for r in equiv.load(out)] == ["uv"]
