"""Tests for the argv/env equivalence harness. #235, #264, #149

The port is not equivalent to the shell by blank equality; it is equivalent
except where a bug is being fixed, and each fix is a deliberate difference. So
assertion 3 does not say "the argv are the same"; it pins the *sanctioned*
difference -- the shell's `--skip-tensor-gate` (which #264 removed from run.py)
against the port's `--allow-unverified-route`, plus the `--server-log` the port
carries because the shell redirected stdout instead.

The fixtures under `tests/fixtures/equiv/` are the recorded emissions of both
drivers; they were generated by `scripts/gen_equiv_fixtures.py` and committed,
so these tests run offline with no driver loop, server, or GPU.
"""

from __future__ import annotations

import datetime as dt
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
for sub in ("scripts", "scripts/lib", "benchmarks/agent"):
    sys.path.insert(0, str(ROOT / sub))

import equiv
import pytest
import route_ab_report

FIXTURES = ROOT / "tests" / "fixtures" / "equiv"
PORT = FIXTURES / "route_agent_ab-port.jsonl"
SHELL = FIXTURES / "route_agent_ab-shell.jsonl"

TAG = "t-sweep1"


# ------------------------------------------------------------------ the model


def test_invocation_roundtrips_through_jsonl(tmp_path) -> None:
    inv = equiv.Invocation("ds4-server", "t", ["--metal", "-m", "m"], {"A": "1"})
    path = tmp_path / "rec.jsonl"
    equiv.record(path, inv)
    got = equiv.load(path)
    assert got == [inv]
    assert got[0].program == "ds4-server"
    assert got[0].argv == ("--metal", "-m", "m")
    assert got[0].env == {"A": "1"}


def test_load_skips_blank_and_comment_lines(tmp_path) -> None:
    path = tmp_path / "rec.jsonl"
    path.write_text(
        "# source: route_agent_ab.sh\n"
        '{"program": "run.py", "arm": "t", "argv": ["--backend"], "env": {}}\n'
        "\n"
    )
    got = equiv.load(path)
    assert len(got) == 1 and got[0].program == "run.py"


def test_by_program_filters(tmp_path) -> None:
    p = tmp_path / "r.jsonl"
    equiv.record(p, equiv.Invocation("ds4-server", "t", [], {}))
    equiv.record(p, equiv.Invocation("run.py", "t", [], {}))
    assert [i.program for i in equiv.by_program(equiv.load(p), "run.py")] == ["run.py"]


def test_env_key_state_distinguishes_every_meaning() -> None:
    assert equiv.env_key_state({}, "K") == "absent"
    assert equiv.env_key_state({"K": ""}, "K") == "empty"
    assert equiv.env_key_state({"K": "1"}, "K") == "set:1"


# ---------------------------------------------------------- the shim itself


def test_write_shim_records_argv_and_env_through_child_run(tmp_path) -> None:
    """The shim works, and `child.run`'s unset reaches the recorded child.

    The host exports an operator's leftover of the #149 variable; the reference
    arm must strip it anyway, and the fake proves it by recording the child's
    env without the key. This is the mechanism assertion 2 rests on.
    """
    out = tmp_path / "rec.jsonl"
    shim = equiv.write_shim(tmp_path / "shim", out)
    for arm in ("t", "r"):
        if arm == "t":
            equiv.run_fake(
                shim,
                "ds4-server",
                arm,
                ["--port", "8000"],
                {equiv.TENSOR_ENV: "1"},
                (),
                out,
                tmp_path / "spawn.log",
                via="ds4-server",
            )
        else:
            equiv.run_fake(
                shim,
                "ds4-server",
                arm,
                ["--port", "8000"],
                {},
                (equiv.TENSOR_ENV,),
                out,
                tmp_path / "spawn.log",
                via="ds4-server",
            )
    recs = equiv.by_program(equiv.load(out), "ds4-server")
    assert len(recs) == 2
    assert equiv.env_key_state(recs[0].env, equiv.TENSOR_ENV) == "set:1"
    assert equiv.env_key_state(recs[1].env, equiv.TENSOR_ENV) == "absent"


# ---------------------------------------------------------- run.py's flags


def test_declared_run_flags_reads_live_source(tmp_path) -> None:
    fake = tmp_path / "run.py"
    fake.write_text(
        "import argparse\n"
        "p = argparse.ArgumentParser()\n"
        "p.add_argument('--trials', type=int, default=1)\n"
        "p.add_argument('-v', '--verbose', action='store_true')\n"
    )
    flags = equiv.declared_run_flags(fake)
    for want in ("--trials", "-v", "--verbose", "-h", "--help"):
        assert want in flags


def test_run_py_declares_the_ports_flag_not_the_shells():
    flags = equiv.declared_run_flags()
    assert "--allow-unverified-route" in flags
    assert "--server-log" in flags
    assert "--skip-tensor-gate" not in flags  # #264 removed it


def test_assert_flags_declared_ignores_values_and_names_unknown():
    flags = frozenset({"--trials", "--no-lock"})
    equiv.assert_flags_declared(["--trials", "3", "--no-lock"], flags)  # no raise
    with pytest.raises(AssertionError):
        equiv.assert_flags_declared(["--trials", "3", "--skip-tensor-gate"], flags)
    # a value is not a flag
    equiv.assert_flags_declared(["--trials", "3", "path/to/model"], flags)


# ---------------------------------------------------- canonical / argv diff


def test_canonical_drops_flag_order_keeps_flag_value():
    flags = frozenset({"--a", "--b", "--v"})
    c1 = equiv.canonical(["--a", "1", "--b", "2"], flags)
    c2 = equiv.canonical(["--b", "2", "--a", "1"], flags)
    assert c1 == c2
    # flipping a flag's value is a change
    assert equiv.canonical(["--a", "1"], flags) != equiv.canonical(["--a", "2"], flags)


def test_canonical_does_not_glue_an_unknown_flag_onto_the_previous():
    flags = frozenset({"--no-lock"})
    got = equiv.canonical(["--no-lock", "--skip-tensor-gate"], flags)
    assert ("--skip-tensor-gate",) in got  # it opens its own pair, not a value
    assert ("--no-lock",) in got


def test_argv_difference_only_reports_the_two_sides_true_diff():
    declared = frozenset({"--no-lock", "--a"})
    shell_only, port_only = equiv.argv_difference(
        ["--no-lock", "--skip-tensor-gate"], ["--no-lock", "--a"], declared
    )
    assert shell_only == {("--skip-tensor-gate",)}
    assert port_only == {("--a",)}
    # --no-lock appears on both, so it is not in the diff


# ---------------------------------------------- assertion 4: the tag consumer


def route_consumer(tag: str, tmp_path: pathlib.Path) -> str | None:
    """route_ab_report's own window parser, fed one sweep line."""
    run_dir = tmp_path / "run"
    run_dir.mkdir(exist_ok=True)
    (run_dir / "sweep-order.txt").write_text(f"{tag} 08:00:00 08:10:00\n")
    # tz-aware is only to satisfy ruff: read_windows reads the anchor's .date()
    # and then builds naive windows, so awareness is irrelevant to the result.
    anchor = dt.datetime(2026, 9, 9, 8, tzinfo=dt.UTC)
    wins = route_ab_report.read_windows(run_dir, "t-sweep", "r-sweep", anchor)
    return wins[0][1] if wins else None


def test_the_driver_tag_roundtrips_through_its_report(tmp_path):
    equiv.assert_tag_roundtrips(TAG, "t", lambda t: route_consumer(t, tmp_path))


def test_the_bare_default_tag_is_unparseable(tmp_path):
    """Without tag_for the ab_driver default ships a tag nobody can read."""
    for bad in equiv.default_tags():
        assert route_consumer(bad, tmp_path) is None, bad


# ---------------------------------------------- the committed fixtures (1-3)


def test_assertion1_the_ports_flags_are_all_declared():
    flags = equiv.declared_run_flags()
    for run in equiv.by_program(equiv.load(PORT), "run.py"):
        equiv.assert_flags_declared(run.argv, flags)


def test_assertion1_the_shells_skip_tensor_gate_is_gone():
    """The shell still passes --skip-tensor-gate (#264); run.py dropped it.

    This is why the harness records the shell as the *expected-broken* side,
    not as a target the port must match: had the port reproduced the shell's
    flag, assertion 1 would fail on the port too.
    """
    flags = equiv.declared_run_flags()
    shell_run = equiv.by_program(equiv.load(SHELL), "run.py")[0]
    with pytest.raises(AssertionError):
        equiv.assert_flags_declared(shell_run.argv, flags)


def test_assertion2_env_difference_matches_between_the_drivers():
    for fixture in (SHELL, PORT):
        equiv.assert_arm_env_delta(equiv.load(fixture), key=equiv.TENSOR_ENV)


def test_assertion2_ds4_server_only_not_run_py(tmp_path) -> None:
    """The run.py client is not asserted; a leftover on it fails nothing.

    The experiment's variable is the route the *server* takes, so the env delta
    is asserted on the server's child only. To prove the scope, give the run.py
    client a state that would fail assertion 2 if it were checked (a leftover
    "7" that is neither set:1 nor absent) and assert `assert_arm_env_delta`
    still passes -- the client is simply not the subject of #149, and the port
    must not be forced to strip the operator's export from its client env.
    """
    out = tmp_path / "rec.jsonl"
    shim = equiv.write_shim(tmp_path / "shim", out)
    equiv.run_fake(
        shim,
        "ds4-server",
        "r",
        [],
        {},
        (equiv.TENSOR_ENV,),
        out,
        tmp_path / "s.log",
        via="ds4-server",
    )
    equiv.run_fake(
        shim,
        "run.py",
        "r",
        [],
        {equiv.TENSOR_ENV: "7"},
        (),
        out,
        tmp_path / "s.log",
        via="run.py",
    )
    recs = equiv.load(out)
    equiv.assert_arm_env_delta(recs, key=equiv.TENSOR_ENV)  # only checks server
    run_env = equiv.by_program(recs, "run.py")[0].env
    assert equiv.env_key_state(run_env, equiv.TENSOR_ENV) == "set:7"


def test_assertion3_server_argv_is_identical_between_the_drivers():
    flags = equiv.declared_run_flags()
    for arm in ("t", "r"):
        shell_srv = equiv.by_program(equiv.load(SHELL), "ds4-server")
        port_srv = equiv.by_program(equiv.load(PORT), "ds4-server")
        s = next(x for x in shell_srv if x.arm == arm)
        p = next(x for x in port_srv if x.arm == arm)
        assert equiv.canonical(s.argv, flags) == equiv.canonical(p.argv, flags)


def test_assertion3_run_py_diff_is_exactly_the_sanctioned_fixes():
    flags = equiv.declared_run_flags()
    shell_run = equiv.by_program(equiv.load(SHELL), "run.py")[0].argv
    port_run = equiv.by_program(equiv.load(PORT), "run.py")[0].argv
    shell_only, port_only = equiv.argv_difference(shell_run, port_run, flags)
    assert shell_only == {("--skip-tensor-gate",)}  # #264, and only that
    # the port adds exactly the #264 fix and the --server-log (the shell
    # redirected stdout to a log instead of telling run.py where to write).
    assert port_only == {
        ("--allow-unverified-route",),
        ("--server-log", "out/server-t-sweep1.log"),
    }
    # both sides name the same backend, trials, client -- the measurement inputs
    for side in (shell_run, port_run):
        assert "--backend" in side and "--client" in side and "--trials" in side
