"""Shared state collection for the peer tooling. #160

`peer_brief.py` and `peer_status.py` both read the same machine and repo
state: the run lock, the resident model servers, the `~/git/ds4-*` trees and
their drift, the repo HEAD and dirty paths, and the NEXT.md top 10. That state
is the shared bus between agents -- the filesystem and git, not a server -- so
it is collected once here and rendered differently by the two scripts.

The machine half comes from `preflight`, which owns the run lock and the
server census; the tree half comes from `staleness`, which owns the #70
ancestor check. This module does not re-derive either. It only enumerates the
trees and the NEXT.md list, which neither owns.
"""

from __future__ import annotations

import os
import pathlib
import platform
import re
import subprocess
import sys

sys.path.insert(
    0, str(pathlib.Path(__file__).resolve().parents[2] / "benchmarks" / "agent")
)
import preflight
import staleness

HOME = pathlib.Path.home()
GIT_DIR = HOME / "git"
REPO = GIT_DIR / "local-llm"
NEXT_MD = REPO / "NEXT.md"
ORG = "evanwtf/local-llm"


def _run(argv: list[str]) -> str | None:
    """Run a command, return trimmed stdout, or None on any failure.

    A failure is an absence, not an error: an offline `gh` or a missing tree
    must read as "unknown", never as a crash.
    """
    try:
        proc = subprocess.run(
            argv, capture_output=True, text=True, check=False, timeout=30
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    return proc.stdout.strip() or None


def ds4_trees() -> list[pathlib.Path]:
    """Every `~/git/ds4-*` checkout, sorted. [] when none."""
    if not GIT_DIR.is_dir():
        return []
    return sorted(p for p in GIT_DIR.glob("ds4-*") if (p / ".git").exists())


def tree_drift(tree: pathlib.Path) -> dict | None:
    """The #70 ancestor check for one tree, via staleness."""
    return staleness.git_drift(tree)


def run_lock() -> tuple[str, str]:
    """(state, why) for the run lock, via preflight. State is one of
    free/ours/held/stale/foreign/corrupt."""
    lock = preflight.read_lock(preflight.LOCK_PATH)
    return preflight.lock_state(lock, platform.node(), os.getpid())


def servers() -> list[preflight.Proc]:
    """Resident model servers with age, via preflight's own census."""
    text = preflight._capture(["ps", "-eo", "pid,rss,etime,command"])
    return preflight.parse_ps(text)


def git_head(repo: pathlib.Path) -> str | None:
    """Short HEAD rev, or None when the repo is missing."""
    return _run(["git", "-C", str(repo), "rev-parse", "--short", "HEAD"])


def git_dirty(repo: pathlib.Path) -> list[str]:
    """Porcelain dirty paths, or [] when clean."""
    out = _run(["git", "-C", str(repo), "status", "--porcelain"])
    if not out:
        return []
    return [line for line in out.splitlines() if line.strip()]


def commits_since(repo: pathlib.Path, ref: str) -> list[str]:
    """One-line commit subjects since `ref`, newest first. [] on failure."""
    out = _run(["git", "-C", str(repo), "log", "--oneline", f"{ref}..HEAD"])
    if not out:
        return []
    return [line for line in out.splitlines() if line.strip()]


# NEXT.md is generated by scripts/make_next.py (#231), and its heading and
# item shape are that script's output. This parse existing separately is the
# point: comparing the parsed file against the live labels is what detects a
# STALE NEXT.md, which is the only way the two can now disagree.
#
# It broke silently once. The generator landed with `## The queue -- 5 P0,
# 4 P1` and items reading `1. **P0 [#151](...)** title`, and this still
# matched `## The top 10` and an item with no priority prefix. It returned
# [], every issue's comment count read as 0, and `peer_status` reported
# "#39: 19 -> 0 comments" for the whole queue -- a peer comment would have
# been invisible. The tests all stubbed next_top10, so nothing failed.
SECTION = re.compile(r"^## The queue\b.*?\n(.*?)(?=^## )", re.MULTILINE | re.DOTALL)
ITEM = re.compile(r"^(\d+)\. \*\*(?:(P\d) )?\[#(\d+)\]\([^)]*\)\*\* (.*)")


def next_top10() -> list[dict]:
    """The NEXT.md queue as [{rank, issue, priority, title}], in rank order.

    Parsed from the section between the `## The queue` heading and the next
    `##`, so a numbered list elsewhere in the file cannot leak in.
    """
    try:
        text = NEXT_MD.read_text()
    except OSError:
        return []
    section = SECTION.search(text)
    if not section:
        return []
    items = []
    for line in section.group(1).splitlines():
        m = ITEM.match(line)
        if m:
            items.append(
                {
                    "rank": int(m.group(1)),
                    "priority": m.group(2),
                    "issue": int(m.group(3)),
                    "title": m.group(4),
                }
            )
    return items


def open_p0p1() -> list[dict]:
    """Open P0 and P1 issues as [{number, title, labels}]. [] on failure.

    `--limit 200` is deliberate: `gh issue list` defaults to 30 and silently
    undercounts, and a P0 that never appears is a P0 nobody acts on.
    """
    out = _run(
        [
            "gh",
            "issue",
            "list",
            "-R",
            ORG,
            "--state",
            "open",
            "--label",
            "P0",
            "--label",
            "P1",
            "--limit",
            "200",
            "--json",
            "number,title,labels",
        ]
    )
    if not out:
        return []
    try:
        import json

        return json.loads(out)
    except ValueError:
        return []


def peer_branches(repo: pathlib.Path = REPO) -> list[dict]:
    """Local `peer/*` branches as [{name, head}], sorted by name. [] on failure."""
    out = _run(
        [
            "git",
            "-C",
            str(repo),
            "for-each-ref",
            "--format=%(refname:short)%09%(objectname:short)",
            "refs/heads/peer/*",
        ]
    )
    if not out:
        return []
    branches = []
    for line in out.splitlines():
        name, _, head = line.partition("\t")
        if name and head:
            branches.append({"name": name, "head": head})
    return branches


def open_prs() -> list[dict]:
    """Open PRs as [{number, title, headRefName}]. [] on failure."""
    out = _run(
        [
            "gh",
            "pr",
            "list",
            "-R",
            ORG,
            "--state",
            "open",
            "--limit",
            "200",
            "--json",
            "number,title,headRefName",
        ]
    )
    if not out:
        return []
    try:
        import json

        return json.loads(out)
    except ValueError:
        return []


def comment_counts(issues: list[int]) -> dict[int, int]:
    """{issue: comment count} for the given issues. Missing on failure."""
    counts: dict[int, int] = {}
    for issue in issues:
        out = _run(["gh", "issue", "view", str(issue), "-R", ORG, "--json", "comments"])
        if not out:
            continue
        try:
            import json

            counts[issue] = len(json.loads(out).get("comments", []))
        except ValueError:
            continue
    return counts
